# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import bloomberg_pb2 as bloomberg__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2

GRPC_GENERATED_VERSION = '1.65.1'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.66.0'
SCHEDULED_RELEASE_DATE = 'August 6, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in bloomberg_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class KeyManagerStub(object):
    """Key management
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.requestKey = channel.unary_unary(
                '/bloomberg.KeyManager/requestKey',
                request_serializer=bloomberg__pb2.KeyRequestId.SerializeToString,
                response_deserializer=bloomberg__pb2.KeyResponse.FromString,
                _registered_method=True)


class KeyManagerServicer(object):
    """Key management
    """

    def requestKey(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_KeyManagerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'requestKey': grpc.unary_unary_rpc_method_handler(
                    servicer.requestKey,
                    request_deserializer=bloomberg__pb2.KeyRequestId.FromString,
                    response_serializer=bloomberg__pb2.KeyResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'bloomberg.KeyManager', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('bloomberg.KeyManager', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class KeyManager(object):
    """Key management
    """

    @staticmethod
    def requestKey(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/bloomberg.KeyManager/requestKey',
            bloomberg__pb2.KeyRequestId.SerializeToString,
            bloomberg__pb2.KeyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class SessionsManagerStub(object):
    """Bloomberg API session management
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.getDefaultOptions = channel.unary_unary(
                '/bloomberg.SessionsManager/getDefaultOptions',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=bloomberg__pb2.SessionOptions.FromString,
                _registered_method=True)
        self.openSession = channel.unary_unary(
                '/bloomberg.SessionsManager/openSession',
                request_serializer=bloomberg__pb2.SessionOptions.SerializeToString,
                response_deserializer=bloomberg__pb2.Session.FromString,
                _registered_method=True)
        self.subscriptionStream = channel.unary_stream(
                '/bloomberg.SessionsManager/subscriptionStream',
                request_serializer=bloomberg__pb2.Session.SerializeToString,
                response_deserializer=bloomberg__pb2.SubscriptionDataResponse.FromString,
                _registered_method=True)
        self.subscribe = channel.unary_unary(
                '/bloomberg.SessionsManager/subscribe',
                request_serializer=bloomberg__pb2.Session.SerializeToString,
                response_deserializer=bloomberg__pb2.Session.FromString,
                _registered_method=True)
        self.unsubscribe = channel.unary_unary(
                '/bloomberg.SessionsManager/unsubscribe',
                request_serializer=bloomberg__pb2.Session.SerializeToString,
                response_deserializer=bloomberg__pb2.Session.FromString,
                _registered_method=True)
        self.sessionInfo = channel.unary_unary(
                '/bloomberg.SessionsManager/sessionInfo',
                request_serializer=bloomberg__pb2.Session.SerializeToString,
                response_deserializer=bloomberg__pb2.Session.FromString,
                _registered_method=True)
        self.closeSession = channel.unary_unary(
                '/bloomberg.SessionsManager/closeSession',
                request_serializer=bloomberg__pb2.Session.SerializeToString,
                response_deserializer=bloomberg__pb2.Session.FromString,
                _registered_method=True)
        self.historicalDataRequest = channel.unary_unary(
                '/bloomberg.SessionsManager/historicalDataRequest',
                request_serializer=bloomberg__pb2.HistoricalDataRequest.SerializeToString,
                response_deserializer=bloomberg__pb2.HistoricalDataResponse.FromString,
                _registered_method=True)
        self.heartbeat = channel.unary_unary(
                '/bloomberg.SessionsManager/heartbeat',
                request_serializer=bloomberg__pb2.Session.SerializeToString,
                response_deserializer=bloomberg__pb2.Session.FromString,
                _registered_method=True)


class SessionsManagerServicer(object):
    """Bloomberg API session management
    """

    def getDefaultOptions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def openSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def subscriptionStream(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def subscribe(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def unsubscribe(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def sessionInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def closeSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def historicalDataRequest(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def heartbeat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SessionsManagerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'getDefaultOptions': grpc.unary_unary_rpc_method_handler(
                    servicer.getDefaultOptions,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=bloomberg__pb2.SessionOptions.SerializeToString,
            ),
            'openSession': grpc.unary_unary_rpc_method_handler(
                    servicer.openSession,
                    request_deserializer=bloomberg__pb2.SessionOptions.FromString,
                    response_serializer=bloomberg__pb2.Session.SerializeToString,
            ),
            'subscriptionStream': grpc.unary_stream_rpc_method_handler(
                    servicer.subscriptionStream,
                    request_deserializer=bloomberg__pb2.Session.FromString,
                    response_serializer=bloomberg__pb2.SubscriptionDataResponse.SerializeToString,
            ),
            'subscribe': grpc.unary_unary_rpc_method_handler(
                    servicer.subscribe,
                    request_deserializer=bloomberg__pb2.Session.FromString,
                    response_serializer=bloomberg__pb2.Session.SerializeToString,
            ),
            'unsubscribe': grpc.unary_unary_rpc_method_handler(
                    servicer.unsubscribe,
                    request_deserializer=bloomberg__pb2.Session.FromString,
                    response_serializer=bloomberg__pb2.Session.SerializeToString,
            ),
            'sessionInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.sessionInfo,
                    request_deserializer=bloomberg__pb2.Session.FromString,
                    response_serializer=bloomberg__pb2.Session.SerializeToString,
            ),
            'closeSession': grpc.unary_unary_rpc_method_handler(
                    servicer.closeSession,
                    request_deserializer=bloomberg__pb2.Session.FromString,
                    response_serializer=bloomberg__pb2.Session.SerializeToString,
            ),
            'historicalDataRequest': grpc.unary_unary_rpc_method_handler(
                    servicer.historicalDataRequest,
                    request_deserializer=bloomberg__pb2.HistoricalDataRequest.FromString,
                    response_serializer=bloomberg__pb2.HistoricalDataResponse.SerializeToString,
            ),
            'heartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.heartbeat,
                    request_deserializer=bloomberg__pb2.Session.FromString,
                    response_serializer=bloomberg__pb2.Session.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'bloomberg.SessionsManager', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('bloomberg.SessionsManager', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SessionsManager(object):
    """Bloomberg API session management
    """

    @staticmethod
    def getDefaultOptions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/bloomberg.SessionsManager/getDefaultOptions',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            bloomberg__pb2.SessionOptions.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def openSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/bloomberg.SessionsManager/openSession',
            bloomberg__pb2.SessionOptions.SerializeToString,
            bloomberg__pb2.Session.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def subscriptionStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/bloomberg.SessionsManager/subscriptionStream',
            bloomberg__pb2.Session.SerializeToString,
            bloomberg__pb2.SubscriptionDataResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def subscribe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/bloomberg.SessionsManager/subscribe',
            bloomberg__pb2.Session.SerializeToString,
            bloomberg__pb2.Session.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def unsubscribe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/bloomberg.SessionsManager/unsubscribe',
            bloomberg__pb2.Session.SerializeToString,
            bloomberg__pb2.Session.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def sessionInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/bloomberg.SessionsManager/sessionInfo',
            bloomberg__pb2.Session.SerializeToString,
            bloomberg__pb2.Session.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def closeSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/bloomberg.SessionsManager/closeSession',
            bloomberg__pb2.Session.SerializeToString,
            bloomberg__pb2.Session.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def historicalDataRequest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/bloomberg.SessionsManager/historicalDataRequest',
            bloomberg__pb2.HistoricalDataRequest.SerializeToString,
            bloomberg__pb2.HistoricalDataResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def heartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/bloomberg.SessionsManager/heartbeat',
            bloomberg__pb2.Session.SerializeToString,
            bloomberg__pb2.Session.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
