# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gBLP.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ngBLP.proto\x12\x04gblp\"3\n\x0cHelloRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x15\n\rnum_greetings\x18\x02 \x01(\t\"\x1d\n\nHelloReply\x12\x0f\n\x07message\x18\x01 \x01(\t\"(\n\nSumRequest\x12\x0c\n\x04num1\x18\x01 \x01(\x05\x12\x0c\n\x04num2\x18\x02 \x01(\x05\"\x1d\n\x0bSumResponse\x12\x0e\n\x06result\x18\x01 \x01(\x05\x32r\n\x0cMultiGreeter\x12\x34\n\x08sayHello\x12\x12.gblp.HelloRequest\x1a\x10.gblp.HelloReply\"\x00\x30\x01\x12,\n\x03sum\x12\x10.gblp.SumRequest\x1a\x11.gblp.SumResponse\"\x00\x42\x0f\n\x07\x65x.grpc\xa2\x02\x03HSWb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gBLP_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\007ex.grpc\242\002\003HSW'
  _globals['_HELLOREQUEST']._serialized_start=20
  _globals['_HELLOREQUEST']._serialized_end=71
  _globals['_HELLOREPLY']._serialized_start=73
  _globals['_HELLOREPLY']._serialized_end=102
  _globals['_SUMREQUEST']._serialized_start=104
  _globals['_SUMREQUEST']._serialized_end=144
  _globals['_SUMRESPONSE']._serialized_start=146
  _globals['_SUMRESPONSE']._serialized_end=175
  _globals['_MULTIGREETER']._serialized_start=177
  _globals['_MULTIGREETER']._serialized_end=291
# @@protoc_insertion_point(module_scope)
